# Generated by Django 3.2.6 on 2021-08-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='shortened',
            new_name='key',
        ),
    ]
