# Generated by Django 3.2.6 on 2021-08-28 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shortner', '0002_rename_shortened_url_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
