# Generated by Django 3.2.6 on 2021-08-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortner', '0003_url_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
