# Generated by Django 3.2.6 on 2021-08-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortner', '0005_alter_url_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
